import json
import os

SEED_FILE = 'server/seeds/vocabulary_seed.json'

new_words = [
    # --- English Elementary ---
    {"language": "en", "level": "Elementary", "word": "Family", "phonetic": "/ˈfæm.əl.i/", "meaning": "A group of people related by blood or marriage", "meaning_zh": "家庭", "part_of_speech": "Noun", "examples": [{"sentence": "My family lives in London.", "translation": "我的家人住在伦敦。"}], "image": "👨‍👩‍👧‍👦"},
    {"language": "en", "level": "Elementary", "word": "Water", "phonetic": "/ˈwɔː.tər/", "meaning": "A clear liquid that falls as rain", "meaning_zh": "水", "part_of_speech": "Noun", "examples": [{"sentence": "Can I have a glass of water?", "translation": "能给我一杯水吗？"}], "image": "💧"},
    {"language": "en", "level": "Elementary", "word": "Apple", "phonetic": "/ˈæp.əl/", "meaning": "A round fruit with red or green skin", "meaning_zh": "苹果", "part_of_speech": "Noun", "examples": [{"sentence": "I eat an apple every day.", "translation": "我每天吃一个苹果。"}], "image": "🍎"},
    {"language": "en", "level": "Elementary", "word": "School", "phonetic": "/skuːl/", "meaning": "A place where children go to be educated", "meaning_zh": "学校", "part_of_speech": "Noun", "examples": [{"sentence": "School starts at 8:00 AM.", "translation": "学校早上8点上课。"}], "image": "🏫"},
    {"language": "en", "level": "Elementary", "word": "Happy", "phonetic": "/ˈhæp.i/", "meaning": "Feeling or showing pleasure", "meaning_zh": "快乐的", "part_of_speech": "Adjective", "examples": [{"sentence": "She looks very happy today.", "translation": "她今天看起来很开心。"}], "image": "😊"},
    {"language": "en", "level": "Elementary", "word": "Red", "phonetic": "/red/", "meaning": "The color of blood or fire", "meaning_zh": "红色", "part_of_speech": "Adjective", "examples": [{"sentence": "He is wearing a red shirt.", "translation": "他穿着一件红衬衫。"}], "image": "🔴"},
    {"language": "en", "level": "Elementary", "word": "Dog", "phonetic": "/dɒɡ/", "meaning": "A common animal with four legs", "meaning_zh": "狗", "part_of_speech": "Noun", "examples": [{"sentence": "The dog is barking.", "translation": "狗在叫。"}], "image": "🐶"},
    {"language": "en", "level": "Elementary", "word": "Cat", "phonetic": "/kæt/", "meaning": "A small animal with fur", "meaning_zh": "猫", "part_of_speech": "Noun", "examples": [{"sentence": "The cat is sleeping on the sofa.", "translation": "猫在沙发上睡觉。"}], "image": "🐱"},
    {"language": "en", "level": "Elementary", "word": "Book", "phonetic": "/bʊk/", "meaning": "A written or printed work", "meaning_zh": "书", "part_of_speech": "Noun", "examples": [{"sentence": "I am reading a good book.", "translation": "我正在读一本好书。"}], "image": "📖"},
    {"language": "en", "level": "Elementary", "word": "Friend", "phonetic": "/frend/", "meaning": "A person you know well and like", "meaning_zh": "朋友", "part_of_speech": "Noun", "examples": [{"sentence": "Ideally, a friend is a person who offers help when you need it.", "translation": "理想情况下，朋友是在你需要时提供帮助的人。"}], "image": "🤝"},
    
    # --- English Intermediate ---
    {"language": "en", "level": "Intermediate", "word": "Challenge", "phonetic": "/ˈtʃæl.ɪndʒ/", "meaning": "Something that needs great mental or physical effort", "meaning_zh": "挑战", "part_of_speech": "Noun", "examples": [{"sentence": "Climbing the mountain was a real challenge.", "translation": "爬这座山是一个真正的挑战。"}], "image": "🧗"},
    {"language": "en", "level": "Intermediate", "word": "Decision", "phonetic": "/dɪˈsɪʒ.ən/", "meaning": "A choice that you make about something", "meaning_zh": "决定", "part_of_speech": "Noun", "examples": [{"sentence": "It was a difficult decision to make.", "translation": "这是一个艰难的决定。"}], "image": "🤔"},
    {"language": "en", "level": "Intermediate", "word": "Experience", "phonetic": "/ɪkˈspɪə.ri.əns/", "meaning": "Knowledge or skill from doing something", "meaning_zh": "经验", "part_of_speech": "Noun", "examples": [{"sentence": "Do you have any experience in sales?", "translation": "你有销售经验吗？"}], "image": "💼"},
    {"language": "en", "level": "Intermediate", "word": "opportunity", "phonetic": "/ˌɒp.əˈtjuː.nə.ti/", "meaning": "An occasion or situation that makes it possible to do something", "meaning_zh": "机会", "part_of_speech": "Noun", "examples": [{"sentence": "This is a great opportunity for you.", "translation": "这对你来说是一个绝佳的机会。"}], "image": "🚪"},
    {"language": "en", "level": "Intermediate", "word": "Suggest", "phonetic": "/səˈdʒest/", "meaning": "To mention an idea for people to consider", "meaning_zh": "建议", "part_of_speech": "Verb", "examples": [{"sentence": "I suggest we wait a bit longer.", "translation": "我建议我们再等一会儿。"}], "image": "💡"},
    {"language": "en", "level": "Intermediate", "word": "Environment", "phonetic": "/ɪnˈvaɪ.rən.mənt/", "meaning": "The air, water, and land in or on which people, animals, and plants live", "meaning_zh": "环境", "part_of_speech": "Noun", "examples": [{"sentence": "We should protect the environment.", "translation": "我们应该保护环境。"}], "image": "🌍"},
    {"language": "en", "level": "Intermediate", "word": "Behavior", "phonetic": "/bɪˈheɪ.vjər/", "meaning": "The way that someone behaves", "meaning_zh": "行为", "part_of_speech": "Noun", "examples": [{"sentence": "His behavior was very strange.", "translation": "他的行为非常奇怪。"}], "image": "🎭"},
    {"language": "en", "level": "Intermediate", "word": "Available", "phonetic": "/əˈveɪ.lə.bəl/", "meaning": "Able to be bought, used, or reached", "meaning_zh": "可获得的；有空的", "part_of_speech": "Adjective", "examples": [{"sentence": "Is this seat available?", "translation": "这个座位有人吗？"}], "image": "🪑"},
    {"language": "en", "level": "Intermediate", "word": "Community", "phonetic": "/kəˈmjuː.nə.ti/", "meaning": "The people living in one particular area", "meaning_zh": "社区", "part_of_speech": "Noun", "examples": [{"sentence": "He is well known in the local community.", "translation": "他在当地社区很有名。"}], "image": "🏘️"},
    {"language": "en", "level": "Intermediate", "word": "Process", "phonetic": "/ˈprəʊ.ses/", "meaning": "A series of actions that you take in order to achieve a result", "meaning_zh": "过程", "part_of_speech": "Noun", "examples": [{"sentence": "Learning a language is a slow process.", "translation": "学习语言是一个缓慢的过程。"}], "image": "⚙️"},

    # --- English Common Phrases ---
    {"language": "en", "level": "Common Phrases", "word": "Bite the bullet", "phonetic": "/baɪt ðə ˈbʊl.ɪt/", "meaning": "To force yourself to do something unpleasant", "meaning_zh": "咬紧牙关（硬着头皮做）", "part_of_speech": "Idiom", "examples": [{"sentence": "I hate going to the dentist, but I'll just have to bite the bullet.", "translation": "我讨厌看牙医，但我只能硬着头皮去了。"}], "image": "😬"},
    {"language": "en", "level": "Common Phrases", "word": "Call it a day", "phonetic": "/kɔːl ɪt ə deɪ/", "meaning": "To stop what you are doing because you do not want to do any more or think you have done enough", "meaning_zh": "收工；今天就到这里", "part_of_speech": "Idiom", "examples": [{"sentence": "I'm exhausted. Let's call it a day.", "translation": "我累坏了。今天就到这里吧。"}], "image": "🛑"},
    {"language": "en", "level": "Common Phrases", "word": "Under the weather", "phonetic": "/ˈʌn.də ðə ˈweð.ər/", "meaning": "Slightly ill/sick and not as well as usual", "meaning_zh": "身体不适", "part_of_speech": "Idiom", "examples": [{"sentence": "I'm feeling a bit under the weather today.", "translation": "我今天感觉有点不舒服。"}], "image": "🤒"},
    {"language": "en", "level": "Common Phrases", "word": "Spill the beans", "phonetic": "/spɪl ðə biːnz/", "meaning": "To tell people secret information", "meaning_zh": "泄露秘密", "part_of_speech": "Idiom", "examples": [{"sentence": "Don't spill the beans about the surprise party.", "translation": "别泄露惊喜派对的秘密。"}], "image": "🤫"},
    {"language": "en", "level": "Common Phrases", "word": "Once in a blue moon", "phonetic": "/wʌns ɪn ə bluː muːn/", "meaning": "Very rarely", "meaning_zh": "千载难逢；难得一次", "part_of_speech": "Idiom", "examples": [{"sentence": "I go to the cinema once in a blue moon.", "translation": "我难得去一次电影院。"}], "image": "🌕"},
    {"language": "en", "level": "Common Phrases", "word": "Cost an arm and a leg", "phonetic": "/kɒst ən ɑːm ənd ə leɡ/", "meaning": "To be very expensive", "meaning_zh": "非常昂贵", "part_of_speech": "Idiom", "examples": [{"sentence": "That car costs an arm and a leg.", "translation": "那辆车贵得要命。"}], "image": "💸"},
    {"language": "en", "level": "Common Phrases", "word": "Hit the sack", "phonetic": "/hɪt ðə sæk/", "meaning": "To go to bed in order to sleep", "meaning_zh": "睡觉", "part_of_speech": "Idiom", "examples": [{"sentence": "I'm going to hit the sack. Goodnight!", "translation": "我要去睡觉了。晚安！"}], "image": "🛌"},

    # --- Chinese Classical (Wenyan) ---
    {"language": "zh", "level": "Classical", "word": "温故知新", "phonetic": "wēn gù zhī xīn", "meaning": "Gain new insights through reviewing old material", "meaning_zh": "Review the old and know the new", "part_of_speech": "Idiom", "examples": [{"sentence": "温故而知新，可以为师矣。", "translation": "Reviewing what you have learned and acquiring new knowledge allows you to be a teacher."}], "image": "📜"},
    {"language": "zh", "level": "Classical", "word": "三人行，必有我师", "phonetic": "sān rén xíng, bì yǒu wǒ shī", "meaning": "There is always something to learn from others", "meaning_zh": "In a group of three, there must be one I can learn from", "part_of_speech": "Quote", "examples": [{"sentence": "孔子曰：“三人行，必有我师焉。”", "translation": "Confucius said: 'When I walk along with two others, they may serve me as my teachers.'"}], "image": "👥"},
    {"language": "zh", "level": "Classical", "word": "己所不欲，勿施于人", "phonetic": "jǐ suǒ bù yù, wù shī yú rén", "meaning": "Do not do to others what you do not want done to yourself", "meaning_zh": "Do not impose on others what you yourself do not desire", "part_of_speech": "Quote", "examples": [{"sentence": "This is the Golden Rule: 己所不欲，勿施于人。", "translation": "这就是金科玉律：己所不欲，勿施于人。"}], "image": "⚖️"},
    {"language": "zh", "level": "Classical", "word": "知彼知己，百战不殆", "phonetic": "zhī bǐ zhī jǐ, bǎi zhàn bù dài", "meaning": "Know the enemy and know yourself, and you can fight a hundred battles with no danger of defeat", "meaning_zh": "Know yourself and know your enemy, and you will never be defeated", "part_of_speech": "Quote", "examples": [{"sentence": "孙子兵法云：知彼知己，百战不殆。", "translation": "Sun Tzu's Art of War says: Know the enemy and know yourself, and you can fight a hundred battles with no danger of defeat."}], "image": "⚔️"},
    {"language": "zh", "level": "Classical", "word": "有朋自远方来，不亦乐乎", "phonetic": "yǒu péng zì yuǎn fāng lái, bù yì lè hū", "meaning": "Is it not delightful to have friends coming from distant quarters?", "meaning_zh": "有朋友从远方来，不也是很快乐吗？", "part_of_speech": "Quote", "examples": [{"sentence": "We welcomed them with the spirit of '有朋自远方来，不亦乐乎'.", "translation": "我们怀着'有朋自远方来，不亦乐乎'的精神欢迎他们。"}], "image": "🎉"},

    # --- Chinese Poetry ---
    {"language": "zh", "level": "Poetry", "word": "海内存知己，天涯若比邻", "phonetic": "hǎi nèi cún zhī jǐ, tiān yá ruò bǐ lín", "meaning": "A bosom friend afar brings a distant land near.", "meaning_zh": "只要四海之内有知心朋友，即使远在天边也像近邻一样。", "part_of_speech": "Verse", "examples": [{"sentence": "王勃《送杜少府之任蜀州》", "translation": "Wang Bo: Farewell to Vice-Prefect Du Setting Out for his Official Post in Shu"}], "image": "🌏"},
    {"language": "zh", "level": "Poetry", "word": "床前明月光", "phonetic": "chuáng qián míng yuè guāng", "meaning": "The bright moonlight before my bed.", "meaning_zh": "床前的月光。", "part_of_speech": "Verse", "examples": [{"sentence": "李白《静夜思》：床前明月光，疑是地上霜。", "translation": "Li Bai 'Quiet Night Thought': Bright moonlight before my bed, I suspect it is frost on the ground."}], "image": "🌙"},
    {"language": "zh", "level": "Poetry", "word": "春眠不觉晓", "phonetic": "chūn mián bù jué xiǎo", "meaning": "In spring one sleeps, unaware of dawn.", "meaning_zh": "春天的睡眠让人感觉不到天亮。", "part_of_speech": "Verse", "examples": [{"sentence": "孟浩然《春晓》：春眠不觉晓，处处闻啼鸟。", "translation": "Meng Haoran 'Spring Dawn': In spring one sleeps, unaware of dawn; everywhere I hear birds singing."}], "image": "🐦"},
    {"language": "zh", "level": "Poetry", "word": "欲穷千里目，更上一层楼", "phonetic": "yù qióng qiān lǐ mù, gèng shàng yī céng lóu", "meaning": "To see a thousand miles, go up another floor.", "meaning_zh": "想要看到千里之外的景色，就要再登上一层楼。", "part_of_speech": "Verse", "examples": [{"sentence": "王之涣《登鹳雀楼》", "translation": "Wang Zhihuan 'On the Stork Tower'"}], "image": "🏰"},
    {"language": "zh", "level": "Poetry", "word": "采菊东篱下，悠然见南山", "phonetic": "cǎi jú dōng lí xià, yōu rán jiàn nán shān", "meaning": "Picking chrysanthemums under the eastern fence, I calmly see the Southern Mountain.", "meaning_zh": "在东篱下采摘菊花，悠然自得地看见南山。", "part_of_speech": "Verse", "examples": [{"sentence": "陶渊明《饮酒》", "translation": "Tao Yuanming 'Drinking Wine'"}], "image": "🌼"},
]

try:
    with open(SEED_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Append new words
    data.extend(new_words)
    
    with open(SEED_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
        
    print(f"Successfully added {len(new_words)} words to {SEED_FILE}")
    
except Exception as e:
    print(f"Error: {e}")
